DROP SCHEMA IF EXISTS FPL CASCADE;
CREATE SCHEMA IF NOT EXISTS FPL;

CREATE TABLE FPL.APP_USER
(

    ID         BIGINT,
    LOGIN      VARCHAR(50)  NOT NULL UNIQUE,
    PASSWORD   VARCHAR(256) NOT NULL,
    USER_STATE VARCHAR(50)  NOT NULL,
    FIRST_NAME VARCHAR(200),
    LAST_NAME  VARCHAR(200),
    USER_ROLE VARCHAR(200),
    UPDATE_TS  TIMESTAMP WITHOUT TIME ZONE,
    CREATE_TS  TIMESTAMP WITHOUT TIME ZONE

);
ALTER TABLE FPL.APP_USER
    ADD CONSTRAINT PK_APP_USER PRIMARY KEY (ID);
CREATE SEQUENCE FPL.APP_USER_SEQ;

CREATE TABLE FPL.USER_TOKEN
(
    ID          BIGINT,
    TOKEN       VARCHAR(1000)               NOT NULL,
    USER_ID     BIGINT                      NOT NULL,
    TOKEN_STATE VARCHAR(50)                 NOT NULL,
    UPDATE_TS   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CREATE_TS   TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
ALTER TABLE FPL.USER_TOKEN
    ADD CONSTRAINT PK_USER_TOKEN PRIMARY KEY (ID);
ALTER TABLE FPL.USER_TOKEN
    ADD CONSTRAINT FK_TOKEN_USER_ID FOREIGN KEY (USER_ID) REFERENCES FPL.APP_USER (ID);
CREATE SEQUENCE FPL.USER_TOKEN_SEQ;

CREATE TABLE FPL.WORD
(
    ID BIGINT,
    WORD VARCHAR(200) NOT NULL UNIQUE,
    UPDATE_TS   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CREATE_TS   TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

ALTER TABLE FPL.WORD
    ADD CONSTRAINT PK_WORD PRIMARY KEY (ID);
CREATE SEQUENCE FPL.WORD_SEQ;

CREATE TABLE FPL.TRANSLATE
(
    ID BIGINT,
    WORD_ID BIGINT,
    VALUE VARCHAR(200) NOT NULL,
    UPDATE_TS   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CREATE_TS   TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

ALTER TABLE FPL.TRANSLATE
    ADD CONSTRAINT PK_TRANSLATE PRIMARY KEY (ID);
ALTER TABLE FPL.TRANSLATE
    ADD CONSTRAINT FK_TRANSLATE_WORD_ID FOREIGN KEY (WORD_ID) REFERENCES FPL.WORD(ID);
CREATE SEQUENCE FPL.TRANSLATE_SEQ;

CREATE TABLE FPL.APP_USER_WORD
(
    ID BIGINT,
    USER_ID BIGINT,
    WORD_ID BIGINT,
    UPDATE_TS   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CREATE_TS   TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

ALTER TABLE FPL.APP_USER_WORD
    ADD CONSTRAINT PK_USER_WORD PRIMARY KEY (ID);
ALTER TABLE FPL.APP_USER_WORD
    ADD CONSTRAINT FK_APP_USER_ID FOREIGN KEY (USER_ID) REFERENCES FPL.APP_USER(ID);
ALTER TABLE FPL.APP_USER_WORD
    ADD CONSTRAINT FK_WORD_ID FOREIGN KEY (WORD_ID) REFERENCES FPL.WORD(ID);
CREATE SEQUENCE FPL.APP_USER_WORD_SEQ;


